[package]
name = "tgt_gd_introduction_project"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
tungstenite = { version = "0.27.0", features = ["native-tls"] }
